<div class="container">
  <div class="d-flex justify-content-center mt-5">
    <div class="card" style="width: 36rem;">
      <div class="card-body">

        <div class="d-flex justify-content-center">
          <img src="/img/logo.png" />
        </div>

        <div class="row">
          <div class="col">
            <h2>Cadastre sua conta</h2>
          </div>
        </div>

        <div class="row">
          <div class="col">
            
            <form action="/registrar" method="post">
             
            <div class="form-group">
                <input type="text" value="<?= $this->view->usuario['userid'] ?>" name="userid" class="form-control" placeholder="UserID">
              </div>

              <div class="form-group">
                <input type="text" value="<?= $this->view->usuario['name'] ?>" name="name" class="form-control" placeholder="Name">
              </div>

              <div class="form-group">
                <input type="text" value="<?= $this->view->usuario['email'] ?>" name="email" class="form-control" placeholder="E-mail">
              </div>

              <div class="form-group">
                <input type="password" value="<?= $this->view->usuario['password'] ?>" name="password" class="form-control" placeholder="Password">
              </div>

              <div class="form-group">
                <input type="password" value="<?= $this->view->usuario['confirmpassword'] ?>" name="confirmpassword" class="form-control" placeholder="Confirm Password">
              </div>

              
              <div class="mt-4 mb-4">
                <small class="form-text">
                Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.
                </small>
              </div>
              <button type="submit" class="btn btn-primary btn-block">Cadastrar</button>
              <a href="https://www.google.com/" class="btn btn-primary btn-block">Clique aqui para fazer o download</a>
              <?php if($this->view->erroCadastro) { ?>

                <small class="form-text text-danger">*Erro ao tentar realizar o cadastro, verifique se os campos foram preenchidos corretamente.</small>

              <?php } ?>
              
            </form>

          </div>
        </div>

      </div>
    </div>
  </div>
</div>